services:
  postgres:
    image: postgres:15
    container_name: muffin-postgres
    environment:
      POSTGRES_DB: muffin_wallet
      POSTGRES_USER: muffin-wallet
      POSTGRES_PASSWORD: muffin-wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U muffin-wallet"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  muffin-network:
    driver: bridge

volumes:
  postgres_data:
