global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://victoria-metrics:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 10000
      max_shards: 30

scrape_configs:
  - job_name: 'muffin-wallet'
    static_configs:
      - targets: ['muffin-wallet.local:30090']
        labels:
          namespace: 'muffin'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'victoria-metrics'
    static_configs:
      - targets: ['victoria-metrics:8428']
        labels:
          namespace: 'monitoring'
          service: 'victoria-metrics'
    metrics_path: '/metrics'
    scrape_interval: 30s