apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-wallet.resource-name" . }}
  labels:
    {{ include "muffin-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "muffin-wallet.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "muffin-wallet.selector" . | nindent 8 }}
        version: {{ .Values.version | default "v1" }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "muffin-wallet.resource-name" .) }}
      volumes:
        # Application config volume
        - name: application-config-volume
          configMap:
            name: {{ .Values.configMaps.application.name }}
        # Logs volume for promtail
        - name: app-logs
          emptyDir: {}
        # Promtail config volume
        - name: promtail-config
          configMap:
            name: promtail-config
      containers:
      # Main application container
      - name: {{ .Values.appLabel }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
          - name: application-config-volume
            mountPath: /app/config
          - name: app-logs
            mountPath: /logs
        envFrom:
          {{- range .Values.envFrom.secrets }}
          - secretRef:
              name: {{ . }}
          {{- end }}
          {{- range .Values.envFrom.configMaps }}
          - configMapRef:
              name: {{ . }}
          {{- end }}
        {{ include "muffin-wallet.liveness" . | nindent 8 }}
        {{ include "muffin-wallet.readiness" . | nindent 8 }}
      # Promtail sidecar container
      - name: promtail
        image: grafana/promtail:latest
        args:
          - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
          - name: app-logs
            mountPath: /logs
          - name: promtail-config
            mountPath: /etc/promtail/promtail.yaml
            subPath: promtail.yaml