apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-wallet.resource-name" . }}
  labels:
    {{ include "muffin-wallet.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8081'
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "muffin-wallet.selector" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}