meshConfig:
  defaultConfig:
    proxyStatsMatcher:
      inclusionRegexps:
        - ".*circuit_breakers.*"
        - ".*upstream_rq_retry.*"
        - ".*upstream_rq_timeout.*"
      inclusionPrefixes:
        - "circuit_breakers"
        - "upstream_rq_retry"
        - "upstream_rq_timeout"
  enablePrometheusMerge: true
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  defaultProviders:
    tracing:
      sampling: 100.0
      zipkin:
        address: jaeger-collector.istio-system.svc.cluster.local:9411
pilot:
  traceSampling: 100.0
  env:
    PILOT_ENABLE_WORKLOAD_ENTRY_CROSS_CLUSTER: "false"

