prometheus:
  prometheusSpec:
    retention: 30d
    evaluationInterval: 15s
    scrapeInterval: 15s
    scrapeTimeout: 10s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    # additionalScrapeConfigs:
    #   - job_name: 'istio-mesh'
    #     kubernetes_sd_configs:
    #       - role: endpoints
    #         namespaces:
    #           names:
    #             - istio-system
    #             - muffin
    #     relabel_configs:
    #       - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    #         action: keep
    #         regex: istio-telemetry;prometheus
    #   - job_name: 'envoy-stats'
    #     kubernetes_sd_configs:
    #       - role: pod
    #     relabel_configs:
    #       - source_labels: [__meta_kubernetes_pod_container_port_name]
    #         action: keep
    #         regex: '.*-envoy-prom'
    #   - job_name: 'pilot'
    #     kubernetes_sd_configs:
    #       - role: endpoints
    #         namespaces:
    #           names:
    #             - istio-system
    #     relabel_configs:
    #       - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    #         action: keep
    #         regex: istiod;http-monitoring
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
grafana:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  enabled: true
